version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/BookStack"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    target-branch: "feature/dependency-updates"
    commit-message:
      prefix: "deps"
      include: "scope"

  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    target-branch: "feature/dependency-updates"
    commit-message:
      prefix: "deps"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    target-branch: "feature/dependency-updates"
    commit-message:
      prefix: "deps"
      include: "scope"
